[project]
name = "etl-pipeline"
version = "0.1.0"
description = "ETL pipeline with dbt, databricks and airflow"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["dbt-core>=1.10.4", "dbt-databricks>=1.10.4"]
